### ISSUE TITLE
Mac support: Resources path

### ISSUE THREAD

**Issue by Incensum** [traceyobrien/amethyst_engine#1]
The file path for will need to be fixed so that it can work on mac and pc for development. This is currently located in the obj_model.h file. The desired end goal should satisfy these conditions.

- Is global for all objects. (Each object should not have its own copy but should reference a global path)
- Changes depending on the OS.
- Can be changed easily in the code in the future if the path is changed.

**Comment by Azidara** [comment]
This as of now has been implemented although the current mac path is not standard across all macs however this can be changed in the future easily
